import { faker } from '@faker-js/faker';

describe(' ', function () {
  it(' ', function () {
   // const firstName = faker.person.firstName();
   // const lastName = faker.person.lastName();
   // const email = faker.internet.email();
   // const phone = faker.phone.number('##########');

    //import { faker } from '@faker-js/faker';

const invoiceame =
  faker.number.int({ min: 100000, max: 999999 }) +
  faker.string.alpha({ length: 6, casing: 'upper' });

//cy.get('#invoiceNo').type(invoiceNo);



    cy.visit("https://v2qa.lifetrenz.com/#/auth/login")
    cy.xpath("//input[@placeholder='User Name']").type("chandan")
    cy.wait(2000)
    cy.get('[formcontrolname="password"]').type("12345")
    cy.wait(2000)
    cy.xpath("//span[text()='LOGIN']").click()
    cy.wait(2000)

    cy.viewport(1920, 1080);
    cy.xpath("//button[@icon='pi pi-search']").click()
    cy.wait(2000)
    cy.xpath("//input[@placeholder=' Search Application']").type("procurement")
    cy.wait(2000)
    cy.xpath("//label[text()='Procurement']").click()
    cy.wait(5000)

    cy.xpath("//span[.='Create Purchase Order']").click();
    cy.wait(2000)
    cy.xpath("//span[.='New PO']").click();
    cy.wait(2000)
    cy.xpath("//div[2]/span/p-dropdown/div/div").click()
    cy.wait(2000)
    cy.xpath("//div/div/div/div[1]/div/input").type("HealthCare store")
    cy.wait(2000)
    cy.xpath("//span[.='HealthCare Store']").click()
    cy.wait(2000)
    cy.xpath("//span/p-autocomplete/div/input").type("chandan")
    cy.wait(5000)
    cy.xpath("//span[.='Chandan / CHA446']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/div)[3]").click()
    cy.wait(2000)
    cy.xpath("//span[.='Regular PO']").click();
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/div)[5]").click()
    cy.wait(2000)
    cy.xpath("(//span[.='Ramaiah Memorial Hospital'])[3]").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/div)[6]").type("HealthCare Store")
    cy.wait(2000)
    cy.xpath("(//span[.='HealthCare Store'])[3]").click()
    cy.wait(2000)
    //cy.xpath("(//span/p-dropdown/div/span)[6]").click()
    cy.wait(2000)
    //cy.xpath("//span[.='HealthCare Store']").click()
    cy.wait(2000)
    cy.xpath("//p-calendar/span/input").click()
    cy.wait(2000)
    cy.xpath("//span[.='26']").click()
    cy.wait(2000)
    cy.xpath("(//span[.='Add Items'])[1]").click()
    cy.wait(2000)
    cy.xpath("//span[.='From Direct Search']").click()
    cy.wait(2000)
    cy.xpath("//div[1]/div[2]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("(//span[.='Search'])[2]").click()
    cy.wait(2000)
    cy.xpath("(//p-checkbox/div/div[2])[1]").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[1]/td[6]/input").type("100")
    cy.wait(2000)
    cy.xpath("//tbody/tr[2]/td[6]/input").type(100)
    cy.wait(2000)
    cy.xpath("//tbody/tr[3]/td[6]/input").type(100)
    cy.wait(2000)
    cy.xpath("(//span[.='Add Selected Items to PO'])[2]").click()
    cy.wait(2000)
    cy.xpath("//span[.='Other Charges']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Add Charges']").click()
    cy.wait(2000)
    cy.xpath("(//p-dropdown/div/span)[16]").click()
    cy.wait(2000)
    cy.xpath("(//span[.='Other Charges'])[2]").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[2]/input").type("100.50")
    cy.wait(2000)
    cy.xpath("//span[.='Commit']").click()
    cy.wait(2000)
    cy.xpath("//span[.='PO Verification']").click()
    cy.wait(2000)
    cy.xpath("//div/div/table/tbody/tr[1]").click()
    cy.wait(2000)
    cy.xpath("//button[contains(@class,'p-splitbutton-menubutton')]").click()
    cy.wait(2000)
    cy.xpath("//span[.='Verify PO']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Verify PO']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Purchase Order Approval']").click()
    cy.wait(2000)
    cy.xpath("//div/div/table/tbody/tr[1]").click()
    cy.wait(2000)
    cy.xpath("//button[contains(@class,'p-splitbutton-menubutton')]").click()
    cy.wait(2000)
    cy.xpath("//span[.='Approve PO']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Approve PO']").click()
    cy.wait(2000)
    cy.xpath("//div/form/div/textarea").type("PO REMARK")
    cy.wait(2000)
    cy.xpath("(//span[.='Approve PO'])[3]").click();
    cy.wait(2000)
    //po completed
    cy.xpath("//span[.='PO Amendment']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Approved PO']").click()
    cy.wait(2000)
    cy.xpath("//p-table/div/div/table/tbody/tr[1]").click()
    cy.wait(2000)
    cy.xpath("//button[contains(@class,'p-splitbutton-menubutton')]").click()
    cy.wait(2000)
    cy.xpath("//span[.='Create Amendment PO']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Discount']").click()
    cy.wait(2000)
    cy.xpath("(//div/p-dropdown/div/span)[4]").click()
    cy.wait(2000)
    cy.xpath("//p-dropdownitem/li").click()
    cy.wait(2000)
    cy.xpath("(//span/input)[2]").type("10")
    cy.wait(2000)
    cy.xpath("//span[.='Commit Amendment PO']").click()
    cy.wait(2000)
    cy.xpath("//span[.='PO Amendment Approval']").click()
    cy.wait(2000)
    cy.xpath("//div/div/table/tbody/tr[1]").click()
    cy.wait(2000)
    cy.xpath("//button[contains(@class,'p-splitbutton-menubutton')]").click()
    cy.wait(2000)
    cy.xpath("//span[.='Approve Amendment PO']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Approve PO']").click()
    cy.wait(2000)
    cy.xpath("//div/form/div/textarea").type("po amendment approve")
    cy.wait(2000)
    cy.xpath("(//span[.='Approve PO'])[3]").click()
    cy.wait(2000)

  
        

  })
})
