import action from "../../support/action";
import { faker } from '@faker-js/faker';
 const EMRINVOICE =
  faker.number.int({ min: 1000, max: 9999 }) +
  faker.string.alpha({ length: 4, casing: 'upper' });

  const EMR =
  {
    EMR_FLOW: function()
    {
      cy.visit("https://v2qa.lifetrenz.com/");
                cy.wait(2000)
                cy.get(action.username).type("chandan")
                cy.wait(2000)
                cy.get(action.Passward).type("12345");
                cy.wait(2000)
                cy.xpath(action.loginbutton).click()
                cy.wait(2000)
    },
    Emergency_grn_flow: function()
    {
      cy.xpath(action.emr).click()
      //cy.wait(2000)
      cy.xpath(action.new_e_grn).click()
      //cy.wait(2000)
      cy.xpath(action.EMR_INVOICE).type(EMRINVOICE)
      //cy.wait(2000)
      cy.xpath(action.EMR_DC).type(EMRINVOICE)
      //cy.wait(2000)
      cy.xpath(action.e_vendore).type("chandan")
     // cy.wait(5000)
      cy.xpath(action.v_name).click()
     // cy.wait(4000)
      cy.xpath(action.store).click()
     // cy.wait(2000)
      cy.xpath(action.e_store_name).click()
     // cy.wait(2000)
      cy.xpath(action.M_O_T).click()
      //cy.wait(2000)
      cy.xpath(action.e_by_person).click()
      //cy.wait(2000)
      cy.xpath(action.E_SAVE).click()
     cy.wait(2000)
      cy.xpath(action.E_ADD_ITEM).click()
      cy.wait(2000)
      cy.xpath(action.E_TYPE).type("KA11")
      cy.wait(2000)
      cy.xpath(action.E_SEARCH).click()
      cy.wait(2000)
      cy.xpath(action.E_CHECK_BOX).click()
      cy.wait(2000)
      cy.xpath(action.E_ADD_ITEM1).click()
      cy.wait(2000)
      cy.xpath(action.E_BATCH1).type("batch-1")
     // cy.wait(2000)
      cy.xpath(action.E_BATCH2).type("batch-1")
      //cy.wait(2000)
      cy.xpath(action.E_RECIVE_QTY1).type("100")
      //cy.wait(2000)
      cy.xpath(action.E_RECIVE_QTY2).type("100")
      //cy.wait(2000)
      cy.xpath(action.E_RECIVE_QTY3).type("100")
      //cy.wait(2000)
      cy.xpath(action.E_FREE_QTY1).type("5")
      //cy.wait(2000)
      cy.xpath(action.E_FREE_QTY2).type("5")
      //cy.wait(2000)
      cy.xpath(action.E_FREE_QTY3).type("5")
      //cy.wait(2000)
      cy.xpath(action.E_COST_PRICE1).clear().type("100")
      //cy.wait(2000)
      cy.xpath(action.E_COST_PRICE2).clear().type("100")
      //cy.wait(2000)
      cy.xpath(action.E_COST_PRICE3).clear().type("100")
      //cy.wait(2000)
      cy.xpath(action.E_DIS1).clear().type("5")
      //cy.wait(2000)
      cy.xpath(action.E_DIS2).type("5")
      //cy.wait(2000)
      cy.xpath(action.E_DIS3).type("5")
      //cy.wait(2000)
      cy.xpath(action.E_UNIT_MRP).clear().type("100")
      //cy.wait(2000)
      cy.xpath(action.E_OC).click()
      //cy.wait(2000)
      cy.xpath(action.E_ADD_CHARGE).click()
      //cy.wait(2000)
      cy.xpath(action.E_OC_DROP_DOWN).click()
      //cy.wait(2000)
      cy.xpath(action.E_OTC).click()
      //cy.wait(2000)
      cy.xpath(action.E_TYPE1).type("100.5")
      //cy.wait(2000)
      cy.xpath(action.E_REMARK).type("Specification")
      //cy.wait(2000)
      //cy.xpath(action.E_ITEM_DIS).click()
      cy.wait(2000)
      //cy.xpath(action.E_YES).click()
      cy.wait(2000)
      //cy.xpath(action.E_D_DROP_DOWN).click()
      //cy.wait(2000)
      //cy.xpath(action.PER).click()
      //cy.wait(2000)
      //cy.xpath(action.E_DIS_TYPE).type("5")
      cy.wait(2000)
      cy.xpath(action.E_SAVE2).click()
      cy.wait(2000)

    }
    //E_GRN_APPROVE: Function()
   // {

    //}

  }
  export default EMR;