import { faker } from '@faker-js/faker';
describe(' ', function () {
  it(' ', function () {

    const BATCHNO =
      faker.number.int({ min: 100, max: 999 }) +
      faker.string.alpha({ length: 3, casing: 'upper' });
    




    cy.visit("https://v2qa.lifetrenz.com/#/auth/login")
    cy.xpath("//input[@placeholder='User Name']").type("chandan")
    cy.wait(2000)
    cy.get('[formcontrolname="password"]').type("12345")
    cy.wait(2000)
    cy.xpath("//span[text()='LOGIN']").click()
    cy.wait(2000)
    // Stock Addition flow
    cy.viewport(1920, 1080);
    cy.xpath("//button[@icon='pi pi-search']").click()
    cy.wait(2000)
    cy.xpath("//input[@placeholder=' Search Application']").type("inventory")
    cy.wait(2000)
    cy.xpath("//label[.='Inventory']").click()
    cy.wait(5000)
    cy.xpath("//span[.='Stock Movement']").click()
    cy.wait(5000)
    cy.xpath("//span[.='Stock Addition']").click()
    cy.wait(2000)
    cy.xpath("//span[.='New ']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[1]").type("HealthCare Store")
    cy.wait(2000)
    cy.xpath("//span[.='HealthCare Store']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[2]").type("BY PERSON")
    cy.wait(2000)
    cy.xpath("//span[.='BY PERSON']")
    cy.wait(5000)
    cy.xpath("//p-autocomplete/div/input").type("chandan")
    cy.wait(5000)
    cy.xpath("//span[.='Chandan']")
    cy.wait(5000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//tr[.='DOLO 650.11 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath('//table/tbody/tr/td[2]/input').type("batch-1")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[4]/input").type("10")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[6]/input").type("400")
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tr[2]/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.wait(2000)
    cy.xpath("//tr[.='DOLO 650.1 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[2]/td[2]/input").type("batch-1")
    cy.wait(2000)
    cy.xpath("(//table/tbody/tr/td[4]/input)[2]").type("10")
    cy.wait(2000)
    cy.xpath("//div/table/tbody/tr[2]/td[6]/input").type("400")
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[3]/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//tr[.='DOLO 650.1 MG LESS-KA11']").click()
    cy.wait(2000)
    //cy.xpath('//table/tbody/tr/td[2]/input').type("batch-1")
    cy.xpath("//table/tbody/tr[3]/td[4]/input").type("10")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[3]/td[6]/input").type("100")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[3]/td[8]/input").type("400")
    cy.wait(5000)
    cy.xpath("//span[.='Save']").click()
    cy.wait(5000)
    //Stock Addition completed

    cy.xpath("//span[.='Stock Movement']").click()
    cy.wait(5000)
    cy.xpath("//span[.='New Transfer']").click()
    cy.wait(5000)
    cy.xpath("//span[.='New ']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[1]").type("healthcare store")
    cy.wait(2000)
    cy.xpath("//span[.='HealthCare Store']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[2]").type("Main Medical Store")
    cy.wait(2000)
    cy.xpath("//span[.='Main Medical Store']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[3]").click()
    cy.wait(2000)
    cy.xpath("//span[.='BY PERSON']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//tr[.='DOLO 650.11 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath("//tr/td[4]/p-dropdown/div/span").click()
    cy.wait(2000)
    cy.xpath("(//span[.='batch-1'])[1]").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[7]/input").type("10")
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[2]/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.1 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath("(//td[4]/p-dropdown/div/span)[2]").click()
    cy.wait(2000)
    cy.xpath("(//span[.='batch-1'])[2]").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[2]/td[7]/input").type("10")
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[3]/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.1 MG LESS-KA11']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[3]/td[7]/input").type("10")
    cy.wait(3000)
    cy.xpath("//span[.='Save']").click()
    cy.wait(5000)
    // stock transfer completed

    //Receiving Q flow started

    cy.xpath("//span[.='Stock Movement']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Receiving Queue']").click()
    cy.wait(2000)
    cy.xpath("(//span[.='Receive'])[1]").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[1]/td[8]/input").clear().type("6")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[2]/td[8]/input").clear().type("6")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[3]/td[8]/input").clear().type("6")
    cy.wait(5000)
    cy.xpath("//span[.='Confirm']").click()
    cy.wait(5000)
    //Receiving Q flow completed
    //Rejected Stock Items flow
    cy.xpath("//span[.='Stock Movement']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Rejected Stock Transfers']").click()
    cy.wait(2000)
    cy.xpath("(//p-table/div/div[2]/table/tbody/tr)[1]").click()
    cy.wait(2000)
    cy.xpath("//button[contains(@class,'p-splitbutton-menubutton')]").click()
    cy.wait(2000)
    cy.xpath("//span[.='Accept']").click()
    cy.wait(2000)
    //cy.xpath("//div[2]/form/div/div[1]/span/input").type("Rejected Stock Items")
    cy.wait(5000)
    cy.xpath("//span[.='Commit Request']").click()
    cy.wait(5000)
   // Rejected Stock Items flow completed(4 return items)

   //Consumption Stock flow start
    cy.xpath("//span[.='Stock Movement']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Consumption Stock']").click();
    cy.wait(5000)
    cy.xpath("//span[.='New ']").click()
    cy.wait(2000)
    cy.xpath("//span[.='batch-1']").type("healthcare store")
    cy.wait(2000)
    cy.xpath("//span[.='HealthCare Store']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[2]").click()
    cy.wait(2000)
    cy.xpath("//span[.='BY PERSON']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.11 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath("//tr/td[4]/p-dropdown/div/span").click()
    cy.wait(2000)
    cy.xpath("//span[.='batch-1']").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[7]/input").type("10")
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[2]/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.1 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath("(//td[4]/p-dropdown/div/span)[2]").click()
    cy.wait(2000)
    cy.xpath("(//span[.='batch-1'])[3]").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[2]/td[7]/input").type("10")
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[3]/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.1 MG LESS-KA11']").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[3]/td[7]/input").type("10")
    cy.wait(5000)
    cy.xpath("//span[.='Save']").click()
    cy.wait(5000)
    //Consumption Stock flow completed

    //Free Stock flow start
    cy.xpath("//span[.='Stock Movement']").click()
    cy.wait(3000)
    cy.xpath("//span[.='Free Stock']").click()
    cy.wait(2000)
    cy.xpath("//span[.='New ']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[1]").type("healthcare store")
    cy.wait(2000)
    cy.xpath("//span[.='HealthCare Store']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[2]").click()
    cy.wait(2000)
    cy.xpath("//span[.='BY PERSON']").click()
    cy.wait(2000)
    cy.xpath("//span/p-autocomplete/div/input").type("chandan")
    cy.wait(2000)
    cy.xpath("//span[.='Chandan']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.11 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[2]/input").type("BATCH-F1")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[3]/input").type("100")
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[2]/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.1 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[2]/td[2]/input").type("BATCH-F1")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[2]/td[3]/input").type("100")
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr[3]/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.1 MG LESS-KA11']").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[3]/td[3]/input").type("100")
    cy.wait(2000)
    cy.xpath("//span[.='Save']").click()
    //Free Stock flow completed

    //opening stock flow

    cy.xpath("//span[.='Stock Movement']").click()
    cy.wait(3000)
    cy.xpath("//span[.='Opening Stock']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Add New']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[1]").type("healthcare store")
    cy.wait(2000)
    cy.xpath("//span[.='HealthCare Store']").click()
    cy.wait(2000)
    cy.xpath("(//span/p-dropdown/div/span)[2]").click()
    cy.wait(2000)
    cy.xpath("//span[.='BY PERSON']").click()
    cy.wait(2000)
    cy.xpath("(//p-autocomplete/div/input)[2]").type("chandan")
    cy.wait(2000)
    cy.xpath("//span[.='Chandan']").click()
    cy.wait(2000)
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)
    cy.xpath("//tbody/tr/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.11 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[2]/input").type(BATCHNO)
    cy.wait(2000)
    cy.xpath("(//p-calendar/span/input)[2]").click()
    for(let i=0;i<=3;i++)
    {
      cy.xpath("/html/body/div/div[1]/div/div[1]/button[2]").click()
    }
    cy.xpath("//span[.='25']").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[4]/input").type("100")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[6]/input").type("500")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr/td[8]/input").type("600")
    cy.xpath("//span[.='Add']").click()
    cy.wait(2000)

    cy.xpath("//tbody/tr[2]/td[1]/span/input").type("ka11")
    cy.wait(2000)
    cy.xpath("//td[.='DOLO 650.1 MG-KA11']").click()
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[2]/td[2]/input").type(BATCHNO)
    cy.wait(2000)
    cy.xpath("(//p-calendar/span/input)[3]").click()
    for(let i=0;i<=3;i++)
    {
      cy.xpath("/html/body/div/div[1]/div/div[1]/button[2]").click()
    }
    cy.xpath("//span[.='25']").click()

    cy.xpath("//table/tbody/tr[2]/td[4]/input").type("100")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[2]/td[6]/input").type("600")
    cy.wait(2000)
    cy.xpath("//table/tbody/tr[2]/td[8]/input").type("600")
    cy.wait(2000)
    cy.xpath("//span[.='Save']").click()
    cy.wait(2000)
    //opening stock flow completed






  })
})